remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: "The title of your site"
description: "A short description of your site's purpose"
show_downloads: true  # or false, no quotes needed
google_analytics: "UA-XXXXX-Y"  # replace with your actual Google Analytics tracking ID
